apiVersion: apps/v1
kind: Deployment
metadata:
  name: temporal-server
  namespace: temporal
  labels:
    app: temporal-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: temporal-server
  template:
    metadata:
      labels:
        app: temporal-server
    spec:
      containers:
        - name: temporal-server
          image: temporalio/auto-setup:latest
          ports:
            - containerPort: 7233
          env:
            - name: DB
              value: "postgresql"
            - name: POSTGRES_USER
              value: "temporal"
            - name: POSTGRES_PASSWORD
              value: "temporalpassword"
            - name: POSTGRES_HOST
              value: "temporal-db"
          volumeMounts:
            - name: data-volume
              mountPath: /var/lib/temporal
      volumes:
        - name: data-volume
          emptyDir: {}

