apiVersion: v1
kind: Service
metadata:
  name: temporal-web-service
  namespace: temporal
spec:
  selector:
    app: temporal-web
  ports:
    - protocol: TCP
      port: 8088
      targetPort: 8088
  type: NodePort

